//! Native coding-harness metadata and workspace configuration renderers.
//!
//! The provisioner owns managed-file writes; this module owns the adapter-specific
//! paths and content so adding a harness does not grow another provisioner match.

use std::path::PathBuf;

use serde::Serialize;
use serde_json::json;

use crate::provision::MANAGED_MARKER;

const CLAUDE_MD: &str = include_str!("../../engine/workspace_templates/CLAUDE.md");
const GEMINI_MD: &str = include_str!("../../engine/workspace_templates/GEMINI.md");

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum HarnessId {
    Codex,
    ClaudeCode,
    OpenCode,
    GeminiCli,
    CopilotCli,
    Pi,
}

pub struct AdapterOutput {
    pub path: PathBuf,
    pub content: String,
}

pub struct HarnessAdapter {
    pub id: HarnessId,
    pub display_name: &'static str,
    pub executable: &'static str,
    pub skill_root: Option<&'static str>,
    pub render: fn(&str, &str) -> Vec<AdapterOutput>,
    pub render_instructions: fn() -> Vec<AdapterOutput>,
}

impl HarnessAdapter {
    /// MCP-bearing configuration which requires a resolved engine interpreter.
    pub fn mcp_outputs(&self, interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
        (self.render)(interpreter, socket)
    }

    /// Non-MCP instruction files which are useful before the engine is ready.
    pub fn instruction_outputs(&self) -> Vec<AdapterOutput> {
        (self.render_instructions)()
    }

    /// All adapter-owned outputs. Provisioning uses the more specific methods so
    /// it can defer only MCP configuration while the engine interpreter is absent.
    pub fn outputs(&self, interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
        self.mcp_outputs(interpreter, socket)
            .into_iter()
            .chain(self.instruction_outputs())
            .collect()
    }
}

const ADAPTERS: [HarnessAdapter; 6] = [
    HarnessAdapter {
        id: HarnessId::Codex,
        display_name: "Codex",
        executable: "codex",
        skill_root: Some(".agents/skills"),
        render: render_codex,
        render_instructions: no_instruction_outputs,
    },
    HarnessAdapter {
        id: HarnessId::ClaudeCode,
        display_name: "Claude Code",
        executable: "claude",
        skill_root: Some(".claude/skills"),
        render: render_claude_code,
        render_instructions: render_claude_instructions,
    },
    HarnessAdapter {
        id: HarnessId::OpenCode,
        display_name: "OpenCode",
        executable: "opencode",
        skill_root: Some(".opencode/skills"),
        render: render_opencode,
        render_instructions: no_instruction_outputs,
    },
    HarnessAdapter {
        id: HarnessId::GeminiCli,
        display_name: "Gemini CLI",
        executable: "gemini",
        skill_root: Some(".gemini/skills"),
        render: render_gemini_cli,
        render_instructions: render_gemini_instructions,
    },
    HarnessAdapter {
        id: HarnessId::CopilotCli,
        display_name: "Copilot CLI",
        executable: "copilot",
        skill_root: Some(".agents/skills"),
        render: render_copilot_cli,
        render_instructions: no_instruction_outputs,
    },
    HarnessAdapter {
        id: HarnessId::Pi,
        display_name: "Pi",
        executable: "pi",
        skill_root: Some(".agents/skills"),
        render: render_pi,
        render_instructions: no_instruction_outputs,
    },
];

pub fn adapter_registry() -> &'static [HarnessAdapter] {
    &ADAPTERS
}

pub fn adapter(id: HarnessId) -> &'static HarnessAdapter {
    adapter_registry()
        .iter()
        .find(|candidate| candidate.id == id)
        .expect("every HarnessId has a registered adapter")
}

/// All distinct skill roots in adapter display order.
pub fn skill_roots() -> Vec<&'static str> {
    adapter_registry()
        .iter()
        .filter_map(|adapter| adapter.skill_root)
        .fold(Vec::new(), |mut roots, root| {
            if !roots.contains(&root) {
                roots.push(root);
            }
            roots
        })
}

fn output(path: &str, content: impl Into<String>) -> AdapterOutput {
    AdapterOutput {
        path: PathBuf::from(path),
        content: content.into(),
    }
}

fn managed_json(value: serde_json::Value) -> String {
    let mut value = value;
    value["//"] = serde_json::Value::String(format!(
        "{MANAGED_MARKER}: generated by solidifai; safe to overwrite"
    ));
    pretty(&value)
}

fn mcp_server(interpreter: &str, socket: &str) -> serde_json::Value {
    json!({
        "command": interpreter,
        "args": ["-m", "solidifai_mcp"],
        "env": { "SOLIDIFAI_ENGINE_SOCK": socket },
    })
}

fn render_codex(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    vec![output(
        ".codex/config.toml",
        codex_config_toml(interpreter, socket),
    )]
}

fn render_claude_code(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    vec![
        output(
            ".mcp.json",
            managed_json(json!({
                "mcpServers": { "solidifai-cad": mcp_server(interpreter, socket) },
            })),
        ),
        output(
            ".claude/settings.json",
            managed_json(json!({
                "enabledMcpjsonServers": ["solidifai-cad"],
                "hooks": {
                    "SessionStart": [{
                        "hooks": [{
                            "type": "command",
                            "command": claude_session_start_hook(interpreter),
                        }]
                    }]
                }
            })),
        ),
    ]
}

fn render_claude_instructions() -> Vec<AdapterOutput> {
    vec![output("CLAUDE.md", CLAUDE_MD)]
}

fn claude_session_start_hook(interpreter: &str) -> String {
    format!(
        "\"{interpreter}\" -c \"import pathlib; print(pathlib.Path('AGENTS.md').read_text(encoding='utf-8'), end='')\""
    )
}

fn render_opencode(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    let value = json!({
        "$schema": "https://opencode.ai/config.json",
        "mcp": {
            "solidifai-cad": {
                "type": "local",
                "command": [interpreter, "-m", "solidifai_mcp"],
                "environment": { "SOLIDIFAI_ENGINE_SOCK": socket },
                "enabled": true,
            }
        },
        "instructions": ["AGENTS.md"],
    });
    vec![output(
        "opencode.json",
        format!(
            "// {MANAGED_MARKER}: generated by solidifai; safe to overwrite\n{}",
            pretty(&value)
        ),
    )]
}

fn render_gemini_cli(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    vec![output(
        ".gemini/settings.json",
        managed_json(json!({
            "mcpServers": { "solidifai-cad": mcp_server(interpreter, socket) },
        })),
    )]
}

fn render_gemini_instructions() -> Vec<AdapterOutput> {
    vec![output("GEMINI.md", GEMINI_MD)]
}

fn render_copilot_cli(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    vec![output(
        ".github/mcp.json",
        managed_json(json!({
            "mcpServers": {
                "solidifai-cad": {
                    "type": "local",
                    "command": interpreter,
                    "args": ["-m", "solidifai_mcp"],
                    "env": { "SOLIDIFAI_ENGINE_SOCK": socket },
                    "tools": ["*"],
                }
            }
        })),
    )]
}

fn render_pi(interpreter: &str, socket: &str) -> Vec<AdapterOutput> {
    vec![output(
        ".pi/mcp.json",
        managed_json(json!({
            "mcpServers": { "solidifai-cad": mcp_server(interpreter, socket) },
        })),
    )]
}

fn no_instruction_outputs() -> Vec<AdapterOutput> {
    Vec::new()
}

fn codex_config_toml(interpreter: &str, socket: &str) -> String {
    let interpreter = toml_escape(interpreter);
    let socket = toml_escape(socket);
    format!(
        "# {MANAGED_MARKER}: generated by solidifai; safe to overwrite\n\
         \n\
         [mcp_servers.solidifai-cad]\n\
         command = \"{interpreter}\"\n\
         args = [\"-m\", \"solidifai_mcp\"]\n\
         \n\
         [mcp_servers.solidifai-cad.env]\n\
         SOLIDIFAI_ENGINE_SOCK = \"{socket}\"\n"
    )
}

fn toml_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn pretty(value: &serde_json::Value) -> String {
    let mut content = serde_json::to_string_pretty(value).expect("JSON value is serializable");
    content.push('\n');
    content
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::{adapter, adapter_registry, skill_roots, HarnessId};

    const PY: &str = "/abs/python";
    const SOCK: &str = "/abs/engine.sock";

    #[test]
    fn agent_harness_registry_has_the_native_harnesses_in_display_order() {
        assert_eq!(
            adapter_registry().iter().map(|a| a.id).collect::<Vec<_>>(),
            vec![
                HarnessId::Codex,
                HarnessId::ClaudeCode,
                HarnessId::OpenCode,
                HarnessId::GeminiCli,
                HarnessId::CopilotCli,
                HarnessId::Pi,
            ],
        );
        assert!(adapter(HarnessId::GeminiCli)
            .outputs(PY, SOCK)
            .iter()
            .any(|o| o.path == PathBuf::from(".gemini/settings.json")));
    }

    #[test]
    fn agent_harness_registry_exposes_every_distinct_skill_root() {
        assert_eq!(
            skill_roots(),
            vec![
                ".agents/skills",
                ".claude/skills",
                ".opencode/skills",
                ".gemini/skills",
            ]
        );
    }

    #[test]
    fn agent_harness_mcp_renderers_are_parseable_and_preserve_the_stdio_contract() {
        let cases = [
            (HarnessId::Codex, ".codex/config.toml"),
            (HarnessId::ClaudeCode, ".mcp.json"),
            (HarnessId::OpenCode, "opencode.json"),
            (HarnessId::GeminiCli, ".gemini/settings.json"),
            (HarnessId::CopilotCli, ".github/mcp.json"),
            (HarnessId::Pi, ".pi/mcp.json"),
        ];

        for (id, path) in cases {
            let output = adapter(id)
                .outputs(PY, SOCK)
                .into_iter()
                .find(|output| output.path == PathBuf::from(path))
                .unwrap_or_else(|| panic!("{id:?} is missing {path}"));
            assert!(
                output.content.contains("solidifai-managed"),
                "{path} must be managed"
            );

            if id == HarnessId::Codex {
                let value: toml::Value = toml::from_str(&output.content).expect("valid TOML");
                let server = &value["mcp_servers"]["solidifai-cad"];
                assert_eq!(server["command"].as_str(), Some(PY));
                assert_eq!(server["args"][0].as_str(), Some("-m"));
                assert_eq!(server["args"][1].as_str(), Some("solidifai_mcp"));
                assert_eq!(server["env"]["SOLIDIFAI_ENGINE_SOCK"].as_str(), Some(SOCK));
                continue;
            }

            let body = output
                .content
                .lines()
                .filter(|line| !line.trim_start().starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n");
            let value: serde_json::Value = serde_json::from_str(&body).expect("valid JSON");
            let server = match id {
                HarnessId::OpenCode => &value["mcp"]["solidifai-cad"],
                _ => &value["mcpServers"]["solidifai-cad"],
            };
            let command = if id == HarnessId::OpenCode {
                &server["command"][0]
            } else {
                &server["command"]
            };
            let args = if id == HarnessId::OpenCode {
                &server["command"]
            } else {
                &server["args"]
            };
            let env = if id == HarnessId::OpenCode {
                &server["environment"]
            } else {
                &server["env"]
            };
            assert_eq!(command, PY, "{path} command");
            let module_start = usize::from(id == HarnessId::OpenCode);
            assert_eq!(args[module_start], "-m", "{path} -m argument");
            assert_eq!(args[module_start + 1], "solidifai_mcp", "{path} module");
            assert_eq!(env["SOLIDIFAI_ENGINE_SOCK"], SOCK, "{path} socket");
        }
    }

    #[test]
    fn agent_harness_claude_settings_inject_rendered_agents_at_session_start() {
        let settings = adapter(HarnessId::ClaudeCode)
            .outputs(PY, SOCK)
            .into_iter()
            .find(|output| output.path == PathBuf::from(".claude/settings.json"))
            .expect("Claude Code settings output");
        let value: serde_json::Value = serde_json::from_str(&settings.content).expect("valid JSON");
        let command = value["hooks"]["SessionStart"][0]["hooks"][0]["command"]
            .as_str()
            .expect("SessionStart command");
        assert!(command.contains(PY), "hook uses the resolved interpreter");
        assert!(
            command.contains("AGENTS.md"),
            "hook injects workspace instructions"
        );
    }
}
